#!/usr/bin/python
#-*- coding: latin-1 -*-
from subprocess import Popen, PIPE
from scapy.all import *
import socket
import time
import sys
import psutil
import os
import verify_services

# scanner.py contains attacks related to the firewall
# These attacks include 
# => port scanning WAN and LAN  (BRUTAL) and make sure  is not opened in LAN
# => make sur SSL is disabled in LAN
# => 
IP_LAN="192.168.1.40"
IP_WAN=""
port_list={""}
def scan_ports(ip_api,port_list=None,ip_scan=None):
    """
    This methods scan all the ports given in the "port_list" variable. Or all tcp ports by default
    It used NMAP and saves the result in openports.txt
    
    """
    all_ports='-p-'
    if port_list is None:
        port=all_ports;
    else :
        port='-p '+port_list
    process=subprocess.Popen(['nmap','-sS','-Pn','--version-intensity','1','--reason', ip_scan,port,'-oG','openports.txt'])
    #s= os.system("nmap -sS --version-intensity 1 "+ ip +" -p- -oG openports.txt" )
#    process.communicate()
    process.wait() # waits until process terminates before leaving
    if verify_services.service_info(ip_api)==0:
        return True
    else :
        return False
 
def strip_ports():
    """
    This method call the strip_port.sh strip to grep the port number from the results of the scan_ports
    
    """
    process=Popen(['bash', 'strip_ports.sh'])
    time.sleep(2)

#returns 0 => no security problem 
#returns >0 => number of problems
def check_open_ports(port_list=port_list):
    """
    This method print a warwing message if among the ports in ports.txt are port_list. It is used to make sure that that some port are not opened on WAN and LAN
    """
    strip_ports()
    i=0
    try:
        with open('ports.txt') as f:
            for line in f:
                for x in port_list:
                    if (line==(x+"\n")):
                        print "WARNING : Port " + x + " is opened "
                        i=i+1
    except:
        print "ports.txt was not created"
    print str(i) + " ports are opened " 
    if i==0 :
        return False
    return True


def clean_all():
    """
    This method deletes the files (openports.txt and ports.txt) generated by scan_ports() and strip_ports() 
    """
    try:
        os.remove("openports.txt")
        os.remove("ports.txt")
    except :
        pass
